export default Object.freeze({
  AUTH: "auth",
  EMPLOYEE: "employee",
  CLIENT: "client",
  SERVICETASK: "task",
  TICKET: "ticket",
  TIMESHEET: "timesheet",
  EMPTIMESHEET: "empTS",
  CLITIMESHEET: "clientTS",
  TIMESHEET: "timesheet",
  MASTER: "master",
  SERVICE: "services",
  EMPMONITOR: "empMonitor",
  PERMISSIONS: "permissions",
  ATTENDANCE: "attendance",
  DASHBOARD: "dashboard",
  CALENDAR: "calendar",
  MENU: "menu",
  CHARTS: "charts",
  DOCUMENT: "document",
  DOCUMENTTYPE: "documenttype",
  YEAR: "year",
  TASK: "task",
  CLIENT_TYPE: "clienttype",
});
